[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  framework = "#auto"        
  publish = "dev-dist"          

[functions]
    directory = "/netlify/functions/" 

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/manifest.webmanifest"
        [headers.values]
        Content-Type = "application/manifest+json"

[[headers]]
    for = "/assets/*"
    [headers.values]
        cache-control = '''
        max-age=31536000,
        immutable
        '''

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  